<!DOCTYPE html>
<html>
<head>
    <title>Audit Log Sistem</title>
    <style>
        body { font-family: monospace; font-size: 10px; color: #333; }
        
        /* KOP SURAT */
        .kop-table { width: 100%; border-bottom: 3px double #000; margin-bottom: 20px; padding-bottom: 10px; font-family: sans-serif; }
        .kop-logo { width: 60px; text-align: left; vertical-align: middle; }
        .kop-text { text-align: center; vertical-align: middle; }
        .kop-header { font-size: 12pt; font-weight: bold; text-transform: uppercase; margin: 0; }
        .kop-subheader { font-size: 10pt; font-weight: bold; text-transform: uppercase; margin: 2px 0; }
        .kop-address { font-size: 8pt; font-style: italic; }

        .header { margin-bottom: 20px; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
        h1 { font-size: 16px; margin: 0; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ccc; padding: 5px; text-align: left; }
        th { background: #eee; }
        .action-cell { font-weight: bold; color: #000; }
        .security-high { color: red; }
    </style>
</head>
<body>
    <!-- KOP SURAT -->
    <table class="kop-table">
        <tr>
            <td class="kop-logo">
                @if($letterSettings['logo_base64'])
                    <img src="{{ $letterSettings['logo_base64'] }}" style="width: 60px; height: auto;">
                @endif
            </td>
            <td class="kop-text">
                <h1 class="kop-header">{{ $letterSettings['header'] }}</h1>
                <h2 class="kop-subheader">{{ $letterSettings['sub_header'] }}</h2>
                <div class="kop-address">{{ $letterSettings['address'] }}</div>
            </td>
            <td class="kop-logo" style="width: 10px;"></td>
        </tr>
    </table>

    <div class="header">
        <h1>System Audit Log Report</h1>
        <p>Generated at: {{ now()->toDateTimeString() }} | Generated By: System</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 120px;">Timestamp</th>
                <th style="width: 100px;">IP Address</th>
                <th style="width: 150px;">User</th>
                <th style="width: 100px;">Action</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
            <tr>
                <td>{{ $log->created_at }}</td>
                <td>{{ $log->ip_address }}</td>
                <td>{{ $log->user_name }} ({{ $log->user_id }})</td>
                <td class="action-cell">{{ $log->action }}</td>
                <td style="word-wrap: break-word; max-width: 300px;">{{ $log->details }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 20px; font-size: 9px; color: #555; border-top: 1px solid #ddd; padding-top: 5px;">
        {{ $letterSettings['footer'] }}
    </div>
</body>
</html>
